---
  - name: Install python3-pip
    apt: name=python3-pip

  - name: Install virtualenvwrapper on Python3
    pip:
      name: virtualenvwrapper
      executable: pip3

  - name: Create ~/venvs/ folder for "ubuntu" user
    file:
      path: /home/ubuntu/venvs
      owner: ubuntu
      group: ubuntu
      state: directory

  - name: Add WORKON_HOME to ~/.profile
    lineinfile:
      path: /home/ubuntu/.profile
      line: 'export WORKON_HOME=/home/ubuntu/venvs'

  - name: Add VIRTUALENVWRAPPER_PYTHON to ~/.profile
    lineinfile:
      path: /home/ubuntu/.profile
      line: 'export VIRTUALENVWRAPPER_PYTHON=`which python3`'

  - name: Add line to load virtualenvwrapper to ~/.profile
    lineinfile:
      path: /home/ubuntu/.profile
      line: 'source /usr/local/bin/virtualenvwrapper.sh'
